[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"

[[services]]
name = "web"
internal_port = 3000
protocol = "http"

[[services]]
name = "database"
type = "postgres" 